# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - wucols-proxy
      - azure-pipelines-proxy.yml
    exclude:
      - wucols-export
      - azure-pipelines-export.yml

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: "UC Davis CAES Production"

  # Function app name
  functionAppName: "wucols-proxy"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

  # Working Directory
  workingDirectory: "$(System.DefaultWorkingDirectory)/wucols-proxy"

stages:
  - stage: Build
    displayName: Build stage

    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: Bash@3
            displayName: "Build and Publish Function"
            inputs:
              targetType: 'inline'
              script: |
                cd $(workingDirectory)
                echo "Cleaning previous builds..."
                dotnet clean --configuration Release
                
                echo "Restoring packages..."
                dotnet restore
                
                echo "Building function..."
                dotnet build --configuration Release
                
                echo "Publishing function..."
                dotnet publish --configuration Release --output $(System.DefaultWorkingDirectory)/publish_output --self-contained false
                
                echo "Build completed successfully!"

          - task: Bash@3
            displayName: "Verify publish output"
            inputs:
              targetType: 'inline'
              script: |
                echo "Contents of publish_output:"
                ls -la $(System.DefaultWorkingDirectory)/publish_output/
                echo "Looking for metadata files:"
                find $(System.DefaultWorkingDirectory)/publish_output/ -name "*.metadata" -o -name "worker.config.json" -o -name "host.json"
                echo "Checking for executable:"
                ls -la $(System.DefaultWorkingDirectory)/publish_output/wucols-proxy*
                echo "Checking .azurefunctions directory:"
                ls -la $(System.DefaultWorkingDirectory)/publish_output/.azurefunctions/ || echo "No .azurefunctions directory found"
                echo "Checking worker.config.json content:"
                cat $(System.DefaultWorkingDirectory)/publish_output/worker.config.json
                echo "Checking functions.metadata content:"
                cat $(System.DefaultWorkingDirectory)/publish_output/functions.metadata

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: "development"
        pool:
          vmImage: $(vmImageName)

        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  displayName: "Azure functions app deploy"
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    appType: functionAppLinux
                    appName: $(functionAppName)
                    package: "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip"
                    runtimeStack: "DOTNET-ISOLATED|8.0"
                    appSettings: -FUNCTIONS_WORKER_RUNTIME dotnet-isolated -FUNCTIONS_EXTENSION_VERSION ~4
